FROM debian:12.12

# Install iptables package for NAT and routing
RUN apt-get update && apt-get install -y iproute2 ethtool iptables iputils-ping

# Copy the entrypoint script into the container
COPY entrypoint_router.sh /root/entrypoint_router.sh
RUN chmod +x /root/entrypoint_router.sh

# Copy the node_exporter binary into the container
COPY node_exporter/node_exporter /usr/local/bin/node_exporter

WORKDIR /root

ENTRYPOINT ["./entrypoint_router.sh"]
