FROM debian:12.12

# Install iproute2 package to add routes
RUN apt-get update && apt-get install -y iproute2 ethtool iperf3

# Copy the entrypoint script into the container
COPY entrypoint_client.sh /root/entrypoint_client.sh
RUN chmod +x /root/entrypoint_client.sh

# Set the entrypoint to the script
WORKDIR /root
ENTRYPOINT ["sh", "-c", "./entrypoint_client.sh"]