FROM debian:12.12

# Install iptables package for NAT and routing
RUN apt-get update && apt-get install -y iproute2 ethtool iptables iputils-ping

# Copy the entrypoint script into the container
COPY entrypoint_router.sh /root/entrypoint_router.sh
RUN chmod +x /root/entrypoint_router.sh

# Set the entrypoint to the script
WORKDIR /root
ENTRYPOINT ["sh", "-c", "./entrypoint_router.sh"]